### PR TITLE
Updating link for feature requests

### PR DESCRIPTION
**Pull request by karelm**
Updating link for feature requests to point to new location

### CODE REVIEW

**Comment by hamstu** [comment]
@karelm I think this package is totally deprecated now – not used by any app.

**Comment by karelm** [comment]
Thanks @hamstu I had some old logs that showed the output from this package .. so thought it was still being used 😅 thanks for highlighting this 🙌

**Comment by karelm** [comment]
I think this package is still being used in publish: https://github.com/bufferapp/buffer-publish/blob/7242cb66a098b5c601d3c17cd2b553c514edecdd/packages/sidebar/components/Sidebar/index.jsx#L5

**Comment by hamstu** [comment]
@karelm Yeah we do still have the presentational component there, but we only use it for it's middleware / reducer, and it's never rendered.

I think there's a backlogged item to clean that up in Jira, but I'd have to double check. 😄

**Pull request merged**
